---
- hosts: ubuntu
  become: yes

  tasks:

  - name: Sistema actualizado
    ansible.builtin.apt:
      name: "*"
      state: latest
      update_cache: true
    notify: Reiniciar Sistema

  handlers:

  - name: Reiniciar Sistema
    ansible.builtin.reboot:
